modLoader="javafml"
loaderVersion="[1,)"
license="${license}"

[[mixins]]
config="arcanearchives.mixins.json"

[[mods]]
modId="${id}"
version="${version}"
displayName="${name}"
authors="${authors}"
description='''${description}'''

[[dependencies."${id}"]]
modId="neoforge"
type="required"
versionRange="[21.1,)"
ordering="NONE"
side="BOTH"

[[dependencies."${id}"]]
modId="minecraft"
type="required"
versionRange="${minecraft}"
ordering="NONE"
side="BOTH"

[[dependencies."${id}"]]
modId="patchouli"
type="required"
versionRange="[${patchouli}]"
ordering="AFTER"
side="BOTH"
